#!/usr/bin/env python3
"""citation_graph.py — hierarchically-biased co-citation over the deck metagraph (stdlib only).

Reuses the BluePrintCRM citation-algorithm plan:
  co_citation_count(a, b) = number of views (slides) citing both a and b
  folder_proximity(a, b)  = 1 / 2 ** (maxDepth - sharedAncestorDepth)   (parent chain = vault folders)
  combined                = w_co * co_citation + w_prox * folder_proximity   (default 0.7 / 0.3)

Writes metagraph.md idempotently (replace, never append): one section per node with [[wikilinks]] to its
neighbours and a "## Co-cited" table (top-N by combined score).

Presentation-layer guard: exits non-zero listing any view that cites a node lacking a grounded_in path to an
evidence_fact that carries source + locator + quote.

Usage:
  python3 citation_graph.py --graph metagraph.json --out metagraph.md [--top-n 5] [--weights 0.7 0.3] [--dry-run]
"""
import argparse
import json
import sys
from collections import defaultdict
from itertools import combinations


def load_graph(path):
    with open(path, encoding="utf-8") as f:
        g = json.load(f)
    nodes = {n["id"]: n for n in g["nodes"]}
    edges = g.get("edges", [])
    views = g.get("views", [])
    return g, nodes, edges, views


def ancestor_chain(node_id, nodes):
    """Return [root, ..., node_id] following the parent chain (depth order)."""
    chain = []
    seen = set()
    cur = node_id
    while cur is not None and cur in nodes and cur not in seen:
        seen.add(cur)
        chain.append(cur)
        cur = nodes[cur].get("parent")
    chain.reverse()
    return chain


def shared_ancestor_depth(a, b, chains):
    """Depth of the deepest shared ancestor (0 = only the implicit vault root is shared)."""
    ca, cb = chains[a], chains[b]
    d = 0
    for x, y in zip(ca, cb):
        if x == y:
            d += 1
        else:
            break
    return d


def folder_proximity(a, b, chains, max_depth):
    return 1.0 / (2 ** (max_depth - shared_ancestor_depth(a, b, chains)))


def build_co_citation_matrix(views):
    co = defaultdict(int)
    for v in views:
        cites = sorted(set(v.get("cites", [])))
        for a, b in combinations(cites, 2):
            co[(a, b)] += 1
            co[(b, a)] += 1
    return co


def score_pairs(nodes, views, co, chains, max_depth, w_co, w_prox):
    """combined score for every ordered pair that shares at least one view (plus proximity-only neighbours
    are not enumerated for all N^2 pairs; co-cited pairs are the signal, proximity is the tie-breaker)."""
    scores = defaultdict(dict)
    for (a, b), c in co.items():
        scores[a][b] = w_co * c + w_prox * folder_proximity(a, b, chains, max_depth)
    return scores


def grounded_ok(nodes, edges):
    """A node is grounded when it is an evidence_fact with source+locator+quote, or it has a grounded_in edge
    (transitively) to such a node."""
    gi = defaultdict(list)
    for e in edges:
        if e.get("type") == "grounded_in":
            gi[e["from"]].append(e["to"])
    memo = {}

    def ok(n, stack=()):
        if n in memo:
            return memo[n]
        node = nodes.get(n)
        if node is None:
            memo[n] = False
            return False
        if node.get("type") == "evidence_fact":
            at = node.get("attrs", {})
            evs = at.get("evidence") or [{"source": at.get("source"), "locator": at.get("locator"), "quote": at.get("quote")}]
            res = any(ev.get("source") and ev.get("locator") and ev.get("quote") for ev in evs)
            memo[n] = res
            return res
        if n in stack:
            return False
        res = any(ok(t, stack + (n,)) for t in gi.get(n, []))
        memo[n] = res
        return res

    return ok


def guard(nodes, edges, views):
    ok = grounded_ok(nodes, edges)
    failures = []
    for v in views:
        bad = [c for c in v.get("cites", []) if not ok(c)]
        if bad:
            failures.append((v["id"], v.get("title", ""), bad))
    return failures


def neighbours(nodes, edges):
    nb = defaultdict(list)
    for e in edges:
        nb[e["from"]].append((e["to"], e["type"], "out"))
        nb[e["to"]].append((e["from"], e["type"], "in"))
    return nb


def render_md(g, nodes, edges, views, scores, top_n, w_co, w_prox):
    nb = neighbours(nodes, edges)
    view_of = defaultdict(list)
    for v in views:
        for c in v.get("cites", []):
            view_of[c].append(v["id"])
    order = list(g.get("meta", {}).get("node_types") or []) or ["story", "image", "data_problem", "practical_example", "scenario", "gate_cell", "project", "cost_line", "evidence_fact"]
    L = [f"# {g.get('meta', {}).get('title', 'Metagraph')}", "",
         f"Generated by citation_graph.py (idempotent: this file is replaced on every run). Weights: co-citation {w_co}, folder proximity {w_prox}; top-{top_n} neighbours per node. "
         f"Nodes {len(nodes)} · edges {len(edges)} · views {len(views)}.", "",
         "Rule: a view (slide) may cite a node only if the node has a grounded_in path to an evidence_fact carrying source + locator + quote.", "",
         "## Views (planned slides)", ""]
    for v in views:
        L.append(f"- **{v['id']}** — {v['title']} — cites {len(v.get('cites', []))} nodes: " + ", ".join(f"[[{c}]]" for c in v.get("cites", [])))
    L.append("")
    for t in order:
        ids = [n for n in nodes if nodes[n].get("type") == t]
        if not ids:
            continue
        L += [f"# {t} nodes ({len(ids)})", ""]
        for n in ids:
            node = nodes[n]
            at = node.get("attrs", {})
            L += [f"## {n}", "",
                  f"**{node.get('label', '')}** · type `{t}` · depth {node.get('depth')} · parent {('[[' + node['parent'] + ']]') if node.get('parent') else '—'}", ""]
            if t == "evidence_fact":
                L.append(f"- kind: {at.get('kind')} · used by: {', '.join(at.get('used_by', []))}")
                L.append(f"- claim: {at.get('claim', '')}")
                for ev in at.get("evidence", []):
                    L.append(f"- evidence: `{ev.get('source')}` · {ev.get('locator')} · \"{ev.get('quote')}\"")
                if at.get("status"):
                    L.append(f"- status: {at.get('status')}" + (f" (verified {at.get('verified')})" if at.get("verified") else ""))
                if at.get("caveat"):
                    L.append("- caveat: " + " ".join(str(at.get("caveat")).splitlines()))
            else:
                for k, val in at.items():
                    L.append(f"- {k}: {val}")
            if view_of.get(n):
                L.append(f"- cited by views: {', '.join(view_of[n])}")
            byt = defaultdict(list)
            for other, et, d in nb.get(n, []):
                byt[(et, d)].append(other)
            if byt:
                L += ["", "### Edges", ""]
                for (et, d), others in sorted(byt.items()):
                    arrow = "→" if d == "out" else "←"
                    uniq = sorted(set(others))
                    L.append(f"- {et} {arrow} " + ", ".join(f"[[{o}]]" for o in uniq[:40]) + (f" (+{len(uniq) - 40} more)" if len(uniq) > 40 else ""))
            top = sorted(scores.get(n, {}).items(), key=lambda kv: (-kv[1], kv[0]))[:top_n]
            L += ["", "### Co-cited", "", "| Node | Score | Type |", "|---|---|---|"]
            for other, s in top:
                L.append(f"| [[{other}]] | {s:.3f} | {nodes[other].get('type')} |")
            if not top:
                L.append("| — | — | — |")
            L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--graph", required=True)
    ap.add_argument("--out", default=None, help="metagraph.md path (replaced, never appended)")
    ap.add_argument("--top-n", type=int, default=5)
    ap.add_argument("--weights", nargs=2, type=float, default=(0.7, 0.3), metavar=("CO", "PROX"))
    ap.add_argument("--dry-run", action="store_true", help="print top-N neighbours per node; do not write")
    args = ap.parse_args()
    w_co, w_prox = args.weights

    g, nodes, edges, views = load_graph(args.graph)
    max_depth = g.get("meta", {}).get("max_depth") or max(n.get("depth", 1) for n in nodes.values())
    chains = {n: ancestor_chain(n, nodes) for n in nodes}
    co = build_co_citation_matrix(views)
    scores = score_pairs(nodes, views, co, chains, max_depth, w_co, w_prox)

    if args.dry_run:
        for n in nodes:
            top = sorted(scores.get(n, {}).items(), key=lambda kv: (-kv[1], kv[0]))[:args.top_n]
            print(f"{n} ({nodes[n].get('type')}):")
            for other, s in top:
                print(f"    {other:<28} combined={s:.3f} co={co[(n, other)]} prox={folder_proximity(n, other, chains, max_depth):.3f}")
    elif args.out:
        md = render_md(g, nodes, edges, views, scores, args.top_n, w_co, w_prox)
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(md)
        print(f"wrote {args.out}: {len(nodes)} nodes, {len(edges)} edges, {len(views)} views, {sum(1 for _ in co) // 2} co-cited pairs")

    failures = guard(nodes, edges, views)
    if failures:
        print("PRESENTATION-LAYER GUARD FAILED: views citing nodes without a grounded_in path to an evidence_fact:", file=sys.stderr)
        for vid, title, bad in failures:
            print(f"  {vid} {title}: {', '.join(bad)}", file=sys.stderr)
        sys.exit(2)
    print(f"guard OK: every cited node in {len(views)} views is grounded")


if __name__ == "__main__":
    main()
